# Basic
title: Mosicol
subtitle: 网上得来虽很好，觉之此码要键行
welcome_message: <a href="https://objccn.io/products/">我的博客园</a>
description: 嗨，我是Mosicol,专注于软件性能领域的探索，有兴趣和我一起探索吗。
creator: <a href="https://onev.cat">@Mosicol</a>

url: "http://www.mosicol.club"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: '//onev.cat'}
    - {title: 工具, description: 我所使用的工具, url: '/apps'}
    - {title: 订阅, description: 邮件订阅本站, url: '//objccn.io/subscribe'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Mosicol
    # duoshuo:
# Social
social:
    # weibo: onevcat
    github: mosicol
    # twitter: onevcat
    # gplus: 107108267983477358170
    # mail: onev@onevcat.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: onevcat.com
